name: mlops-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - apache-airflow=2.10.5
  - apache-airflow-providers-common-sql
  - apache-airflow-providers-cncf-kubernetes
  - flask
  - flask-login
  - flask-wtf
  - sqlalchemy
  - alembic
  - jinja2
  - pendulum
  - pandas
  - graphviz
