name: mlops-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - apache-airflow[password]==2.7.3
      - -c https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.10.txt
