name: mlops-eda
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - jupyterlab
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn
  - pip
  - pip:
      - ydata-profiling==4.6.4
