name: mlops-experiment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - xgboost
  - optuna
  - jupyterlab
  - ipykernel
  - pycaret=3.3.2
  - mlflow=2.11.3
  - pip
  - pip:
      - optuna-integration[sklearn]
