name: mlops-experiment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - xgboost
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - pycaret==3.3.2
      - mlflow==2.11.3
      - optuna==3.6.1
